# Generated by Django 5.2.5 on 2025-09-29 13:48

from django.db import migrations, models
import random


def generate_account_numbers(apps, schema_editor):
    Wallet = apps.get_model('wallet_management', 'Wallet')

    def get_unique_account_number():
        while True:
            number = str(random.randint(10**9, 10**10 - 1))  # 10-digit number
            if not Wallet.objects.filter(account_number=number).exists():
                return number

    for wallet in Wallet.objects.filter(account_number__isnull=True):
        wallet.account_number = get_unique_account_number()
        wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.RunPython(generate_account_numbers),
    ]
