# Generated by Django 5.2.5 on 2025-09-29 14:04

from django.db import migrations
import random


def generate_account_numbers(apps, schema_editor):
    Wallet = apps.get_model('wallet_management', 'Wallet')
    for wallet in Wallet.objects.filter(account_number__isnull=True):
        while True:
            number = str(random.randint(10**9, 10**10 - 1))  # 10-digit
            if not Wallet.objects.filter(account_number=number).exists():
                wallet.account_number = number
                wallet.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0002_wallet_account_number_alter_wallet_balance'),
    ]

    operations = [
        migrations.RunPython(generate_account_numbers),
    ]
