# Generated by Django 5.2.5 on 2025-09-29 18:58

from django.db import migrations
import random

def generate_account_number(Wallet):
    while True:
        acct_number = str(random.randint(10**9, 10**10 - 1))  # 10-digit number
        if not Wallet.objects.filter(account_number=acct_number).exists():
            return acct_number

def populate_account_numbers(apps, schema_editor):
    Wallet = apps.get_model("wallet_management", "Wallet")
    for wallet in Wallet.objects.filter(account_number__isnull=True):
        wallet.account_number = generate_account_number(Wallet)
        wallet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0003_populate_account_numbers'),
    ]

    operations = [
        migrations.RunPython(populate_account_numbers),
    ]
