# Generated by Django 5.2.5 on 2025-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0004_auto_20250929_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
