# Generated by Django 5.2.5 on 2025-10-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_management', '0005_alter_wallet_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default=0, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
